name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  #test:
  #  runs-on: ${{ matrix.os }}

  #  strategy:
  #    matrix:
  #      deno: ["v1.x", "canary"]
  #      os: [macOS-latest, windows-latest, ubuntu-latest]

  #  steps:
  #    - name: Checkout repo
  #      uses: actions/checkout@v2

  #    - name: Setup Deno
  #      uses: denoland/setup-deno@v1
  #      with:
  #        deno-version: ${{ matrix.deno }}

  #    - name: Verify formatting
  #      if: startsWith(matrix.os, 'ubuntu') && matrix.deno == 'canary'
  #      run: deno fmt --check

  #    - name: Run linter
  #      if: startsWith(matrix.os, 'ubuntu') && matrix.deno == 'canary'
  #      run: deno lint

  #    - name: Cache dependencies
  #      run: deno cache --no-check src/cli/deps.ts src/runtime/deps.ts src/server/deps.ts

  #    - name: Run tests
  #      run: deno test -A --no-check=remote

  #    - name: Type check website
  #      run: deno cache --no-check=remote www/main.ts

  #    - name: Type check examples/counter
  #      run: deno cache --no-check=remote examples/counter/main.ts

  integration-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.x", "canary"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Debug
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Build Fresh
        run: deno install -A -f --no-check -n fresh -r ./cli.ts

      - name: Fresh Init
        run: fresh init foobar

      - name: Check file generation & Move to there
        run: test -d foobar
        working-directory: ./foobar

      - name: Start up the server & Access it
        run: |
          ./main.ts &
          curl localhost:8000

      - name: Type check main.ts
        run: deno cache --no-check=remote main.ts
